[package]
name = "solpda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bs58 = "=0.4.0"
curve25519-dalek = "=3.2.1"
ed25519-dalek = "=1.0.1"
sha2 = "=0.10.2"
